version: "3.8"

services:
  knowledge-hub:
    container_name: knowledge-hub
    build:
      context: .
      dockerfile: Docker/Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  proxy:
    depends_on:
      - knowledge-hub
    restart: unless-stopped
    build:
      dockerfile: Docker/Dockerfile-nginx.dev
    ports:
      - "3000:3000"